#!/usr/bin/env python3
"""
make-favicon.py — the site's icon, from the university's crest.

    python3 scripts/make-favicon.py

Source: assets-src/marks/NTU_logo-ch_1200.png (the owner's file, 1200x1200,
transparent outside the round crest). Writes three files to public/, all at
the site root, where browsers look for them:

  favicon.svg           what every page links (<link rel="icon" … svg>), so no
                        page has to change; an SVG wrapping a 128px PNG of the
                        crest — a traced vector of the crest is not ours to make.
                        ASCII ONLY: it declares no encoding and the server sends
                        none, so a single non-ASCII byte (it once carried the
                        crest's name in Han in a comment) reads as an XML
                        'Encoding error' wherever a copy is decoded as Big5
  favicon.ico           16/32/48/64, for browsers that do not take an
                        SVG icon and look for /favicon.ico (Safari, old Edge)
  apple-touch-icon.png  180x180, the crest on white with a margin: iOS fills a
                        transparent corner with black, and asks for this name
                        at the root even when no page links it

At 16px the crest's lettering is gone and the ring and the plum blossom carry
it — which is what every university's favicon looks like at that size.
"""
import base64, io, pathlib
from PIL import Image, ImageFilter

ROOT = pathlib.Path(__file__).resolve().parents[1]
src = Image.open(ROOT / 'assets-src/marks/NTU_logo-ch_1200.png').convert('RGBA')
src = src.crop(src.getbbox())

def at(px, sharpen=False):
    im = src.resize((px, px), Image.LANCZOS)
    if sharpen:   # a small icon loses its edge in the resample; give a little back
        im = im.filter(ImageFilter.UnsharpMask(radius=0.6, percent=60, threshold=0))
    return im

pub = ROOT / 'public'
sizes = [16, 32, 48, 64]   # tabs, bookmarks and Windows shortcuts; larger is weight nobody sees
icons = [at(s, sharpen=s <= 48) for s in sizes]
icons[-1].save(pub / 'favicon.ico', format='ICO', sizes=[(s, s) for s in sizes], append_images=icons[:-1])

def palette(im):
    # 256 colours with alpha: the crest is flat colour and line, and the file is
    # a third the size of the true-colour one with no difference at icon size
    return im.quantize(colors=256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE)

png = io.BytesIO(); palette(at(128)).save(png, format='PNG', optimize=True)
b64 = base64.b64encode(png.getvalue()).decode('ascii')
(pub / 'favicon.svg').write_text(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128">'
    '<!-- National Taiwan University crest. Generated by scripts/make-favicon.py; ASCII only, see there -->'
    f'<image width="128" height="128" href="data:image/png;base64,{b64}"/>'
    '</svg>\n', encoding='utf-8')

touch = Image.new('RGBA', (180, 180), (255, 255, 255, 255))
crest = at(156); touch.alpha_composite(crest, (12, 12))
touch.convert('RGB').save(pub / 'apple-touch-icon.png', optimize=True)

for f in ('favicon.svg', 'favicon.ico', 'apple-touch-icon.png'):
    print(f'{f:22} {(pub / f).stat().st_size:7} bytes')
